export const GovernanceIcon = () => (
  <svg
    width='24'
    height='24'
    viewBox='0 0 24 24'
    fill='none'
    xmlns='http://www.w3.org/2000/svg'
  >
    <defs>
      <linearGradient
        id='gradient-gov'
        x1='0'
        y1='0'
        x2='24'
        y2='24'
        gradientUnits='userSpaceOnUse'
      >
        <stop offset='0%' stopColor='#0094D4' />
        <stop offset='100%' stopColor='#8E2DE2' />
      </linearGradient>
    </defs>
    <line
      x1='3'
      x2='21'
      y1='22'
      y2='22'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
    />
    <line
      x1='6'
      x2='6'
      y1='18'
      y2='11'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
    />
    <line
      x1='10'
      x2='10'
      y1='18'
      y2='11'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
    />
    <line
      x1='14'
      x2='14'
      y1='18'
      y2='11'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
    />
    <line
      x1='18'
      x2='18'
      y1='18'
      y2='11'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
    />
    <polygon
      points='12 2 20 7 4 7'
      stroke='url(#gradient-gov)'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    />
  </svg>
);
