export const articleCategories = [
  "Technology",
  "Products",
  "Use Cases",
  "Staking",
  "Governance",
  "Tokenomics",
  "Interoperability",
  "Security",
  "Scalability",
  "Guides",
  "Tokenization",
  "Decentralization",
  "Adoption",
  "Ecosystem",
  "Marketing",
  "Education",
  "Analysis",
  "PR",
  "News",
  "Announcement",
  "Blockchain",
] as const;
