import type { LayoutProps, WidgetCategory } from "@/types/homepageTypes";

import { WidgetDataTypes, WidgetTypes } from "@/types/widgetTypes";

import { widgetMinWidth } from "@/constants/widget";

import TxList from "@/resources/images/widgets/RecentTX.svg";
import TxInEpoch from "@/resources/images/widgets/tx_in_epoch_chart.svg";
import EpochsInTime from "@/resources/images/widgets/EpochsInTime.svg";
import EpochList from "@/resources/images/widgets/EpochList.svg";
import PoolList from "@/resources/images/widgets/stakePoolList.svg";
import PoolDetail from "@/resources/images/widgets/poolDetail.svg";
import DrepList from "@/resources/images/widgets/DRepList.svg";
import DrepDetail from "@/resources/images/widgets/drepDetail.svg";
import RecentAssets from "@/resources/images/widgets/RecentAssets.svg";
import AssetDetail from "@/resources/images/widgets/assetDetail.svg";
import RecentBlocks from "@/resources/images/widgets/RecentBlocks.svg";
import LatestBlocks from "@/resources/images/widgets/LatestBlocks.svg";
import BlockProduction from "@/resources/images/widgets/blockProduction.svg";
import BlockSizeUsed from "@/resources/images/widgets/blockSizeUsed.svg";

export const initialLayout: LayoutProps[] = [
  {
    i: "1",
    y: 0,
    static: false,
    x: 0,
    w: 2,
    minW: 2,
    h: 16.8,
    maxH: 16.8,
    minH: 5,
    type: WidgetTypes.TABLE,
    dataType: WidgetDataTypes.BLOCK,
    title: "Block list",
    linkTitle: "All blocks",
    link: "/block",
    rowHeight: 59,
  },
  {
    i: "2",
    y: 0,
    static: false,
    x: 2,
    w: 2,
    minW: 2,
    h: 16.8,
    maxH: 16.8,
    minH: 5,
    type: WidgetTypes.TABLE,
    dataType: WidgetDataTypes.DREP,
    title: "Drep list",
    linkTitle: "All dreps",
    link: "/drep",
  },
  {
    i: "3",
    y: 17,
    static: false,
    x: 0,
    w: 4,
    minW: 2,
    h: 16.8,
    maxH: 16.8,
    minH: 5,
    type: WidgetTypes.TABLE,
    dataType: WidgetDataTypes.POOL,
    title: "Pool list",
    linkTitle: "All pools",
    link: "/pool",
    rowHeight: 49,
  },
];

export const initialWidgetCategories: WidgetCategory[] = [
  {
    title: "Transactions",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.TX,
        title: "Tx list",
        linkTitle: "All TXs",
        link: "/tx",
        img: TxList,
      },
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.GRAPH],
        h: 10.5,
        minH: 5,
        type: WidgetTypes.GRAPH,
        dataType: WidgetDataTypes.TX_IN_EPOCH,
        title: "Transactions in epoch",
        linkTitle: "All TXs",
        link: "/tx",
        img: TxInEpoch,
      },
    ],
  },
  {
    title: "Blocks",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.BLOCK,
        title: "Block list",
        linkTitle: "All blocks",
        link: "/block",
        rowHeight: 59,
        img: RecentBlocks,
      },
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.GRAPH],
        h: 10.5,
        minH: 5,
        type: WidgetTypes.GRAPH,
        dataType: WidgetDataTypes.BLOCK_PRODUCTION,
        title: "Block production",
        linkTitle: "All TXs",
        link: "/tx",
        img: BlockProduction,
      },
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.GRAPH],
        h: 10.5,
        minH: 5,
        type: WidgetTypes.GRAPH,
        dataType: WidgetDataTypes.BLOCK_SIZE_USED,
        title: "Block size used",
        linkTitle: "All TXs",
        link: "/tx",
        img: BlockSizeUsed,
      },
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.GRAPH],
        h: 10.5,
        minH: 5,
        type: WidgetTypes.GRAPH,
        dataType: WidgetDataTypes.LATEST_BLOCKS,
        title: "Latest blocks",
        linkTitle: "All TXs",
        link: "/tx",
        img: LatestBlocks,
      },
    ],
  },
  {
    title: "Drep",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.DREP,
        title: "Drep list",
        linkTitle: "All dreps",
        link: "/drep",
        img: DrepList,
      },
      {
        x: 0,
        w: 2,
        minW: widgetMinWidth[WidgetTypes.DETAIL],
        maxW: 2,
        h: 9.4,
        minH: 5,
        type: WidgetTypes.DETAIL,
        dataType: WidgetDataTypes.DREP_DETAIL,
        title: "Drep detail",
        linkTitle: "",
        link: "/drep",
        img: DrepDetail,
        rowHeight: 49,
      },
    ],
  },
  {
    title: "Asset",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.ASSET,
        title: "Asset list",
        linkTitle: "All assets",
        link: "/asset",
        rowHeight: 59,
        img: RecentAssets,
      },
      {
        x: 0,
        w: 2,
        minW: widgetMinWidth[WidgetTypes.DETAIL],
        maxW: 2,
        h: 9.4,
        minH: 5,
        type: WidgetTypes.DETAIL,
        dataType: WidgetDataTypes.ASSET_DETAIL,
        title: "Asset detail",
        linkTitle: "",
        link: "/asset",
        img: AssetDetail,
        rowHeight: 49,
      },
    ],
  },
  {
    title: "Epoch",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.EPOCH,
        title: "Epoch list",
        linkTitle: "All epochs",
        link: "/epoch",
        img: EpochList,
        rowHeight: 59,
      },
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.GRAPH],
        h: 10.5,
        minH: 5,
        type: WidgetTypes.GRAPH,
        dataType: WidgetDataTypes.EPOCH_BLOCKCHAIN,
        title: "Epochs",
        linkTitle: "All epochs",
        link: "/epoch",
        img: EpochsInTime,
      },
    ],
  },
  {
    title: "Pool",
    widgets: [
      {
        x: 0,
        w: 4,
        minW: widgetMinWidth[WidgetTypes.TABLE],
        h: 16.8,
        maxH: 16.8,
        minH: 5,
        type: WidgetTypes.TABLE,
        dataType: WidgetDataTypes.POOL,
        title: "Pool list",
        linkTitle: "All pools",
        link: "/pool",
        img: PoolList,
        rowHeight: 49,
      },
      {
        x: 0,
        w: 2,
        minW: widgetMinWidth[WidgetTypes.DETAIL],
        maxW: 2,
        h: 9.4,
        minH: 5,
        type: WidgetTypes.DETAIL,
        dataType: WidgetDataTypes.POOL_DETAIL,
        title: "Pool detail",
        linkTitle: "",
        link: "/pool",
        img: PoolDetail,
        rowHeight: 49,
      },
    ],
  },
];
